### ISSUE TITLE
Doesn't Work on BlazorServer with @attribute [RenderModeServer]

### ISSUE THREAD

**Issue by ericpincus** [soenneker/soenneker.blazor.masonry#45]
The tool works as designed with the following at the top of the page:
@page "/test"
@using Soenneker.Blazor.Masonry.Abstract

But then, if I add this line: @attribute [RenderModeServer]

@page "/test"
@using Soenneker.Blazor.Masonry.Abstract
@attribute [RenderModeServer]

It does not function as designed. I need that RenderModeServer line for other purposes.

Via the console, I see the following message:

Bad element for masonry: .container
r @ masonry.pkgd.min.js:9

This error is not present when I remove the attribute above.

Thank you

**Comment by soenneker** [comment]
Thanks for the report - will take a look when I get a chance

**Comment by soenneker** [comment]
@ericpincus I believe this is the case because OnAfterRender is not called in Blazor Server (https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0). Make sure the container is rendered in the DOM before calling the masonry init code.

**Comment by soenneker** [comment]
Closing, feel free to reopen if you have more info, thanks!
